# Site settings
title: Yeji Kim-Barros
email: yeji@kimbarros.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kimbarros.com" # the base hostname & protocol for your site

twitter_username:
github_username: ykbarros
linkedin_url: https://www.linkedin.com/in/yejikimbarros/

# Build settings
markdown: kramdown
plugins:
- jekyll-seo-tag
