# Site setings
name: 'Yeji Kim-Barros'
description: 'the Product Person'
meta_description: 'Product management essays and guides'
baseurl: "" # the subpath of your site, e.g. /blog/
production_url: "https://kimbarros.com" # the base hostname & protocol for your site
url: "https://kimbarros.com"

# Engagement settings
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'AuthorImage.png'
  greetings: "Build product with me: no frills guides, frameworks, case studies, and personal essays that chronicle my product creation process from 0 to 1."
favicon: 'assets/images/favicon.ico'
# disqus: 'justgoodthemes'
# mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: UA-223736039-1
# Add Google Tag Manager Container Id
google:
  tag_manager:
    container_id: GTM-WM9PWMJ
# Contact form settings
email: yeji@kimbarros.com
contact_page_description: "Want to <b>accelerate</b> your experiment and learning cycle <b>without a product org?</b><br>
At the cusp of bringing on a product team but <b>don't know where to begin?</b><br><br>

I can be the multiplier for your team. <br><br>

I can offer:<br>
🗣️ <b>User testing and research</b> to validate your assumptions in the market.<br>
🚩 <b>Usability analysis</b> to ensure you're building a usable, valuable customer experience.<br>
🗺️ <b>Strategy and roadmap</b> to inspire the team behind your vision.<br>
🤝 <b>Team setup and coaching</b> to build an empowered product team.<br>
📈 <b>Product process development and improvement</b> plans that grow with your organization.<br><br>

If I'm the right fit for you, or if you simply want to say hello, please reach out."

thankyou_page_description: "Thanks for your message. I'll get back to you shortly. Cheers!"
# Social links
twitter: #''
facebook: #''
codepen: #''
dribbble: #''
medium: #'@username'
instagram: #''
pinterest: #''
linkedin: 'yejikimbarros'
producthunt: #'@username'
quora: #'username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: Search
    url: /search
  - text: About
    url: /about
  - text: Contact Me
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-google-tag-manager

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Kramdown
kramdown:
    auto_ids: true

# Sass
sass:
  sass_dir: _sass
  style: compressed
